name: Trigger backend builds

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        backend: [haxeui-html5, haxeui-openfl, haxeui-kha, haxeui-hxwidgets, haxeui-nme, haxeui-flixel, haxeui-heaps]

    steps:
    - uses: actions/checkout@v1
    - name: Dispatch event to ${{ matrix.backend }}
      run: |
        export commit_message="$(echo "${{ github.event.head_commit.message }}"|tr -d '\n')"
        curl --fail -X POST https://api.github.com/repos/haxeui/${{ matrix.backend }}/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -H 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' --data "{\"event_type\": \"haxeui-core push: $commit_message\"}"
